name: CI

on:
  pull_request:
    types:
      # opened = new request
      - opened
      # reopened = closed PR is re-opened
      - reopened
      # synchronize = commits on active PR
      - synchronize

jobs:
  lint-vet-test:
    runs-on: ubuntu-latest

    services:
      ivory:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 'spec!@l \\characters'
          POSTGRES_DB: ivoryPgExisting
        ports:
          - 5555:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Verify go mod is tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Run go vet
        run: go vet ./...

      - name: Run Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          $(go env GOPATH)/bin/staticcheck ./...

      # with static analysis of changes done, confirm tests still pass
      - name: Download dependencies
        run: go mod download

      # url.UserPassword("postgres", `spec!@l \\characters`) == postgres:spec%21%40l+%5C%5Ccharacters
      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:spec%21%40l%20%5Ccharacters@localhost:5555/ivoryPgExisting?sslmode=disable
        run: go test ./...
